version: '3'
services:
  clash:
    image: goreng/clash:v0.16.0
    volumes:
      # - ./boslife.yml:/root/.config/clash/config.yaml
      - ./config.yaml:/root/.config/clash/config.yaml
    ports:
      - "127.0.0.1:7890:7890"
      - "127.0.0.1:7891:7891"
      # - "7892:7892"
      - "127.0.0.1:9090:9090"
      - "53:53/udp"
    restart: always
    # When your system is Linux, you can use `network_mode: "host"` directly.
    network_mode: "host"
    container_name: clash