version: '3'
services:
  clash:
    image: goreng/clash
    volumes:
      - ./config.yml:/root/.config/clash/config.yml
    ports:
      - "127.0.0.1:7890:7890"
      - "127.0.0.1:7891:7891"
      - "127.0.0.1:9090:9090"
    restart: always
    # When your system is Linux, you can use `network_mode: "host"` directly.
    network_mode: "host"
    container_name: clash