name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        DOCKER_TAG: goreng/clash:dev
      run: |
        docker build . --file Dockerfile --tag ${DOCKER_TAG}
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ${DOCKER_TAG}
        docker logout
